FROM mcr.microsoft.com/dotnet/sdk:8.0-bookworm-slim-arm64v8 AS builder
    WORKDIR /source
    COPY NBXplorer/NBXplorer.csproj NBXplorer/NBXplorer.csproj
    COPY NBXplorer.Client/NBXplorer.Client.csproj NBXplorer.Client/NBXplorer.Client.csproj
    # Cache some dependencies
    RUN cd NBXplorer && dotnet restore && cd ..
    COPY . .
    RUN cd NBXplorer && \
        dotnet publish --output /app/ --configuration Release

FROM mcr.microsoft.com/dotnet/aspnet:8.0-bookworm-slim-arm64v8
    WORKDIR /app
    RUN mkdir /datadir
    ENV NBXPLORER_DATADIR=/datadir
    VOLUME /datadir
    COPY --from=builder "/app" .
    ENTRYPOINT ["dotnet", "NBXplorer.dll"]
