name: Build Docker image
on:
  workflow_dispatch:
  push:
    tags:
      - '*'
    branches:
      - elenpay-develop

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          labels: |
            commit=${{ github.sha }}
            actions_run=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.linuxamd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}